// src/utils/forensics/fileAnalyzer.js
// Unified forensic scoring pipeline — production-grade metadata firewall

// ─── KEYWORD LISTS ────────────────────────────────────────────────────────────

/**
 * HIGH RISK: Any match immediately hard-caps the final master score to ≤15%.
 * These are explicit AI-generation tool names or deepfake descriptors.
 */
const HIGH_RISK_KEYWORDS = [
  'deepfake', 'deep fake',
  'ai generated', 'ai-generated', '#aigenerated',
  'voice clone', 'voice cloning', 'voice cloned',
  'synthetic voice', 'synthetic audio',
  'heygen', 'hey gen',
  'synthesia',
  'd-id', 'did.com',
  'sora', 'openai sora',
  'kling', 'kling ai',
  'elevenlabs', 'eleven labs',
  'wav2lip',
  'faceswap', 'face swap',
  'runway gen', 'runway ml',
  'invideo ai',
  'pika labs', 'pika ai',
  'luma dream', 'luma ai',
];

/**
 * AI-ADJACENT: Any match hard-caps to ≤40%.
 * These indicate AI-generated or AI-processed content without being absolute proof.
 */
const AI_ADJACENT_KEYWORDS = [
  'ai generated', 'ai-generated', 'generated by ai',
  'created by ai', 'made with ai', 'made by ai',
  'ai voice', 'ai video', 'ai audio',
  'ai art', '#aiart', '#ai',
  'artificial intelligence', 'artificial voice',
  'text to speech', 'text-to-speech', 'tts', 'text2speech',
  'stable diffusion',
  'midjourney', 'mid journey',
  'dall-e', 'dalle',
  'chatgpt', 'gpt-4', 'gpt4', 'openai',
  'machine learning generated', 'computer generated',
  'neural network generated',
  'animation', 'animated',        // strong signal for non-real content
  'cartoon', 'cartoonized',
  '#aivoice', '#aivideo',
  'deepmind', 'adobe firefly',
  'generative ai', 'generative video',
  'comfyui', 'automatic1111',
];

// ─── METADATA FIREWALL ───────────────────────────────────────────────────────

/**
 * Analyzes metadata fields for synthetic AI signals.
 * @param {{ title, description, channel, tags, url, filename }} payload
 * @returns {{ isSyntheticMetadata, matchedKeywords, highRiskKeywords, hardCap, flags, provenanceValue }}
 */
export function analyzeMetadataFirewall(payload = {}) {
  const {
    title = '', description = '', channel = '',
    tags = [], url = '', filename = ''
  } = payload;

  const combined = [
    title, description, channel,
    Array.isArray(tags) ? tags.join(' ') : '',
    url, filename
  ].join(' ').toLowerCase();

  const matchedHighRisk = HIGH_RISK_KEYWORDS.filter(kw => combined.includes(kw));
  const matchedAdjacent = AI_ADJACENT_KEYWORDS.filter(kw => combined.includes(kw));
  // Deduplicate (high-risk terms may also appear in adjacent list)
  const allMatched = [...new Set([...matchedHighRisk, ...matchedAdjacent])];
  const isSyntheticMetadata = allMatched.length > 0;

  // Hard score cap:
  //   High-risk keyword  → master score ≤ 15  (High Threat)
  //   AI-adjacent only   → master score ≤ 40  (Medium–High Threat)
  //   No match           → no cap (100 = unrestricted)
  let hardCap;
  if (matchedHighRisk.length > 0) {
    hardCap = 15;
  } else if (matchedAdjacent.length > 0) {
    hardCap = 40;
  } else {
    hardCap = 100;
  }

  const flags = allMatched.map(kw => ({
    time: '00:00',
    seconds: 0,
    label: matchedHighRisk.includes(kw) ? '⚠ High-Risk AI Signal' : 'AI Metadata Signal',
    detail: `"${kw}" detected in title/metadata`,
  }));

  const provenanceValue = isSyntheticMetadata
    ? `AI marker detected: "${allMatched[0]}"`
    : 'No synthetic metadata markers found';

  return {
    isSyntheticMetadata,
    matchedKeywords: allMatched,
    highRiskKeywords: matchedHighRisk,
    hardCap,
    flags,
    provenanceValue,
  };
}

// ─── MASTER FORENSIC SCORE FORMULA ──────────────────────────────────────────

/**
 * Computes the final master authenticity score using a multi-layer penalty system.
 *
 * Starting score: 100
 * Layer 1 (Metadata) applies a hard ceiling via `metadataRes.hardCap`.
 * Layer 2 (Facial/Vision) applies penalty if face is present (not faceless media).
 * Layer 3 (Audio) applies penalty for TTS/synthetic audio signatures.
 * Final score is clamped [0, 100] then floored by the metadata hard cap.
 *
 * @param {{ metadataRes, facialMetrics, audioMetrics }} params
 * @returns {{ masterScore: number }}
 */
export function computeMasterForensicScore({ metadataRes = {}, facialMetrics = {}, audioMetrics = {} }) {
  const metadataCap = metadataRes.hardCap ?? 100;

  let penalty = 0;

  // ── Layer 3: Audio penalties (max 35 pts) ────────────────────────────────
  if (audioMetrics.hasTtsAudioSignature)       penalty += 25; // TTS/vocoder spectral flatness detected
  if (audioMetrics.hasAbruptDecibelSpikes)     penalty += 10; // Spliced audio / laugh track injection

  // ── Layer 2: Facial penalties — only on face-present video ───────────────
  // Skipped for: audio files, images, faceless B-roll (isFacelessMedia === true)
  if (!facialMetrics.isFacelessMedia) {
    if (facialMetrics.hasUnnaturalMeshSmoothing) penalty += 20; // Near-zero Z-axis variance (AI avatar)
    if (facialMetrics.hasTeleportationJitter)    penalty += 20; // Inter-frame centroid jump ≥ 5%
    if (facialMetrics.hasZeroBlinkRate)          penalty += 25; // No blinks in >10s window
  }

  const rawScore = Math.max(100 - penalty, 0);

  // Apply metadata hard cap as a ceiling — overrides visual confidence
  const masterScore = Math.min(rawScore, metadataCap);

  return { masterScore: Math.max(0, Math.round(masterScore)) };
}
