// src/utils/forensics/fileAnalyzer.js
// Unified forensic scoring pipeline — production-grade multi-modal engine

// ─── KEYWORD TAXONOMY ─────────────────────────────────────────────────────────

/**
 * HIGH RISK: Immediate hard-cap ≤15% (High Threat).
 * Explicit AI tools, deepfake descriptors, or explicit AI video titles.
 */
const HIGH_RISK_KEYWORDS = [
  'deepfake', 'deep fake',
  'ai generated', 'ai-generated', '#aigenerated',
  'ai video', 'ai animated', 'ai story', 'ai movie', 'ai film',
  'voice clone', 'voice cloning', 'voice cloned',
  'synthetic voice', 'synthetic audio', 'synthetic video',
  'heygen', 'hey gen',
  'synthesia',
  'd-id', 'did.com',
  'sora', 'openai sora',
  'kling', 'kling ai',
  'elevenlabs', 'eleven labs',
  'wav2lip',
  'faceswap', 'face swap',
  'runway gen', 'runway ml',
  'invideo ai',
  'pika labs', 'pika ai',
  'luma dream', 'luma ai',
];

/**
 * AI-ADJACENT: Hard-cap ≤40% (Medium–High Threat).
 * Secondary tags, AI tools, or artistic generation markers.
 */
const AI_ADJACENT_KEYWORDS = [
  'generated by ai', 'created by ai', 'made with ai', 'made by ai',
  'ai voice', 'ai audio',
  'ai art', '#aiart', '#ai',
  'artificial intelligence', 'artificial voice',
  'text to speech', 'text-to-speech', 'tts', 'text2speech',
  'stable diffusion',
  'midjourney', 'mid journey',
  'dall-e', 'dalle',
  'chatgpt', 'gpt-4', 'gpt4', 'openai',
  'machine learning generated', 'computer generated',
  'neural network generated',
  'animation', 'animated',
  'cartoon', 'cartoonized',
  '#aivoice', '#aivideo',
  'deepmind', 'adobe firefly',
  'generative ai', 'generative video',
  'comfyui', 'automatic1111',
];

/**
 * Helper: Smart keyword matcher.
 * Uses regex word-boundary \b for short tokens (<= 4 chars or starting with #)
 * to prevent false positives like 'main' matching 'ai' or 'domain' matching 'ai'.
 */
function matchesKeyword(text, keyword) {
  const kw = keyword.toLowerCase();
  const txt = text.toLowerCase();
  if (kw.length <= 4 && !kw.includes(' ')) {
    // Escape special regex characters like #
    const escaped = kw.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
    const regex = new RegExp(`\\b${escaped}\\b`, 'i');
    return regex.test(txt);
  }
  return txt.includes(kw);
}

// ─── METADATA FIREWALL ───────────────────────────────────────────────────────

/**
 * Analyzes metadata fields for synthetic AI signals using word-boundary regex.
 * @param {{ title, description, channel, tags, url, filename }} payload
 * @returns {{ isSyntheticMetadata, matchedKeywords, highRiskKeywords, hardCap, flags, provenanceValue }}
 */
export function analyzeMetadataFirewall(payload = {}) {
  const {
    title = '', description = '', channel = '',
    tags = [], url = '', filename = ''
  } = payload;

  const combined = [
    title, description, channel,
    Array.isArray(tags) ? tags.join(' ') : '',
    url, filename
  ].join(' ');

  const matchedHighRisk = HIGH_RISK_KEYWORDS.filter(kw => matchesKeyword(combined, kw));
  const matchedAdjacent = AI_ADJACENT_KEYWORDS.filter(kw => matchesKeyword(combined, kw));

  const allMatched = [...new Set([...matchedHighRisk, ...matchedAdjacent])];
  const isSyntheticMetadata = allMatched.length > 0;

  let hardCap;
  if (matchedHighRisk.length > 0) {
    hardCap = 15;
  } else if (matchedAdjacent.length > 0) {
    hardCap = 40;
  } else {
    hardCap = 100;
  }

  const flags = allMatched.map(kw => ({
    time: '00:00',
    seconds: 0,
    label: matchedHighRisk.includes(kw) ? '⚠ High-Risk AI Signal' : 'AI Metadata Signal',
    detail: `"${kw}" detected in title/metadata`,
  }));

  const provenanceValue = isSyntheticMetadata
    ? `AI marker detected: "${allMatched[0]}"`
    : 'No synthetic metadata markers found';

  return {
    isSyntheticMetadata,
    matchedKeywords: allMatched,
    highRiskKeywords: matchedHighRisk,
    hardCap,
    flags,
    provenanceValue,
  };
}

// ─── MASTER FORENSIC SCORE FORMULA ──────────────────────────────────────────

/**
 * Computes final master score using multi-layer weighted penalties + cumulative hard caps.
 *
 * @param {{ metadataRes, facialMetrics, audioMetrics, avSyncMetrics }} params
 * @returns {{ masterScore: number }}
 */
export function computeMasterForensicScore({
  metadataRes = {},
  facialMetrics = {},
  audioMetrics = {},
  avSyncMetrics = {},
}) {
  let metadataCap = metadataRes.hardCap ?? 100;

  let penalty = 0;

  // ── Layer 3: Audio penalties (max 35 pts) ────────────────────────────────
  if (audioMetrics.hasTtsAudioSignature)   penalty += 25; // TTS / vocoder spectral flatness > 0.80
  if (audioMetrics.hasAbruptDecibelSpikes) penalty += 10; // Spliced audio / RMS jump > 65%

  // ── Layer 2: Facial penalties (max 65 pts) ───────────────────────────────
  if (!facialMetrics.isFacelessMedia) {
    if (facialMetrics.hasUnnaturalMeshSmoothing) penalty += 20; // Nose Z-variance σ < 0.0008
    if (facialMetrics.hasTeleportationJitter)    penalty += 20; // Inter-frame centroid jump ≥ 5%
    if (facialMetrics.hasZeroBlinkRate)          penalty += 25; // Zero blinks in observation window
  }

  // ── Layer 3+ Python AV-Sync penalties (max 35 pts) ────────────────────────
  if (avSyncMetrics.correlation_score !== undefined && avSyncMetrics.correlation_score < 70) {
    penalty += 20; // Low audio-visual lip-sync cross-correlation
  }
  if (avSyncMetrics.av_sync_status && avSyncMetrics.av_sync_status.includes('Anomaly')) {
    penalty += 15; // Acoustic phoneme phase mismatch
  }

  // ── Cumulative Multi-Signal Hard Cap Stacking ────────────────────────────
  // If metadata is flagged AND physical layers (facial or audio) also flag anomalies,
  // drop hardCap to ≤ 5% (Critical Threat).
  const hasPhysicalAnomalies =
    audioMetrics.hasTtsAudioSignature ||
    facialMetrics.hasUnnaturalMeshSmoothing ||
    facialMetrics.hasTeleportationJitter;

  if (metadataRes.isSyntheticMetadata && hasPhysicalAnomalies) {
    metadataCap = Math.min(metadataCap, 5);
  }

  const rawScore = Math.max(100 - penalty, 0);

  // Apply metadata hard cap ceiling
  const masterScore = Math.min(rawScore, metadataCap);

  return { masterScore: Math.max(0, Math.round(masterScore)) };
}
