// src/utils/forensics/nlpChecker.js
// NLP-based metadata analysis — synced with fileAnalyzer.js keyword taxonomy

const HIGH_RISK_KEYWORDS = [
  'deepfake', 'deep fake',
  'ai generated', 'ai-generated', '#aigenerated',
  'ai video', 'ai animated', 'ai story', 'ai movie', 'ai film',
  'voice clone', 'voice cloning', 'voice cloned',
  'synthetic voice', 'synthetic audio', 'synthetic video',
  'heygen', 'synthesia', 'd-id', 'did.com',
  'sora', 'kling', 'elevenlabs', 'eleven labs',
  'wav2lip', 'faceswap', 'face swap',
  'runway ml', 'pika labs', 'pika ai', 'luma ai',
  'invideo ai',
];

const AI_ADJACENT_KEYWORDS = [
  'generated by ai', 'created by ai', 'made with ai', 'made by ai',
  'ai voice', 'ai audio', 'ai art', '#aiart', '#ai',
  'artificial intelligence', 'artificial voice',
  'text to speech', 'text-to-speech', 'tts', 'text2speech',
  'stable diffusion', 'midjourney', 'dall-e', 'dalle',
  'chatgpt', 'gpt-4', 'openai',
  'machine learning generated', 'computer generated',
  'neural network generated',
  'animation', 'animated', 'cartoon', 'cartoonized',
  '#aivoice', '#aivideo',
  'generative ai', 'generative video',
  'comfyui', 'adobe firefly',
];

/**
 * Standalone NLP metadata scanner.
 * @param {string} text  Raw text (title, description, filename, URL, etc.)
 * @returns {{ isSynthetic, matchedKeywords, highRiskKeywords, hardCap, riskScore }}
 */
export function analyzeMetadataNLP(text) {
  if (!text) return { isSynthetic: false, matchedKeywords: [], highRiskKeywords: [], hardCap: 100, riskScore: 0 };

  const lower = text.toLowerCase();
  const highRisk = HIGH_RISK_KEYWORDS.filter(kw => lower.includes(kw));
  const adjacent = AI_ADJACENT_KEYWORDS.filter(kw => lower.includes(kw));
  const allMatched = [...new Set([...highRisk, ...adjacent])];

  // Hard cap mirrors fileAnalyzer logic
  const hardCap = highRisk.length > 0 ? 15 : adjacent.length > 0 ? 40 : 100;

  // Risk score: 0–100 composite signal strength
  const riskScore = Math.min(highRisk.length * 30 + adjacent.length * 10, 100);

  return {
    isSynthetic: allMatched.length > 0,
    matchedKeywords: allMatched,
    highRiskKeywords: highRisk,
    hardCap,
    riskScore,
  };
}
